const player = document.querySelector('.player')
const video = player.querySelector('.viewer')
const progress = player.querySelector('.progess')
const progressBar = player.querySelector('.progress__filled')
const toggle = player.querySelector('.toggle')
const skipButtons = player.querySelectorAll('[data-skip]')
